package Frames;
import Classes.Aluno;
import Classes.Financeiro;
import Classes.Funcionario;
import Classes.Turma;
import java.util.ArrayList;

public class AbaInicial extends javax.swing.JFrame {
    Financeiro financeiro;
    ArrayList<Aluno> listaAlunos;
    ArrayList<Funcionario> listaFuncionario;
    Turma primeiro;
    
    public AbaInicial(Financeiro financeiro, ArrayList listaA, ArrayList listaF, Turma primeiro) {
        initComponents();
        this.setLocationRelativeTo(null);   //Inicializar no meio
        this.financeiro = financeiro;
        this.listaAlunos = listaA;
        this.listaFuncionario = listaF;  
        this.primeiro = primeiro;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonSair = new javax.swing.JButton();
        TituloGestao = new java.awt.Label();
        jMenuBar2 = new javax.swing.JMenuBar();
        menuAlunos = new javax.swing.JMenu();
        jMenuItemCadAlu = new javax.swing.JMenuItem();
        jMenuItemPesAlu = new javax.swing.JMenuItem();
        jMenuItemNotasAlu = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        menuFuncionarios = new javax.swing.JMenu();
        jMenuItemCadFun = new javax.swing.JMenuItem();
        jMenuItemPesFun = new javax.swing.JMenuItem();
        jMenuItemProfFun = new javax.swing.JMenuItem();
        menuFinanceiro = new javax.swing.JMenu();
        jMenuItemRelFin = new javax.swing.JMenuItem();
        menuTurmas = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema escolar");

        jButtonSair.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButtonSair.setText("Sair");
        jButtonSair.setToolTipText("");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });

        TituloGestao.setAlignment(java.awt.Label.CENTER);
        TituloGestao.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        TituloGestao.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        TituloGestao.setName(""); // NOI18N
        TituloGestao.setPreferredSize(new java.awt.Dimension(250, 70));
        TituloGestao.setText("Gestão Escolar");

        menuAlunos.setText("Alunos");

        jMenuItemCadAlu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jMenuItemCadAlu.setText("Cadastro");
        jMenuItemCadAlu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadAluActionPerformed(evt);
            }
        });
        menuAlunos.add(jMenuItemCadAlu);

        jMenuItemPesAlu.setText("Pesquisar");
        jMenuItemPesAlu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPesAluActionPerformed(evt);
            }
        });
        menuAlunos.add(jMenuItemPesAlu);

        jMenuItemNotasAlu.setText("Notas");
        jMenuItemNotasAlu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNotasAluActionPerformed(evt);
            }
        });
        menuAlunos.add(jMenuItemNotasAlu);

        jMenuItem6.setText("Lista");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        menuAlunos.add(jMenuItem6);

        jMenuBar2.add(menuAlunos);

        menuFuncionarios.setText("Funcionários");

        jMenuItemCadFun.setText("Cadastro");
        jMenuItemCadFun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadFunActionPerformed(evt);
            }
        });
        menuFuncionarios.add(jMenuItemCadFun);

        jMenuItemPesFun.setText("Pesquisar");
        jMenuItemPesFun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPesFunActionPerformed(evt);
            }
        });
        menuFuncionarios.add(jMenuItemPesFun);

        jMenuItemProfFun.setText("Professores");
        jMenuItemProfFun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemProfFunActionPerformed(evt);
            }
        });
        menuFuncionarios.add(jMenuItemProfFun);

        jMenuBar2.add(menuFuncionarios);

        menuFinanceiro.setText("Financeiro");

        jMenuItemRelFin.setText("Relatório");
        jMenuItemRelFin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRelFinActionPerformed(evt);
            }
        });
        menuFinanceiro.add(jMenuItemRelFin);

        jMenuBar2.add(menuFinanceiro);

        menuTurmas.setText("Turmas");

        jMenuItem1.setText("1º Ano");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuTurmas.add(jMenuItem1);

        jMenuItem3.setText("2º Ano");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        menuTurmas.add(jMenuItem3);

        jMenuItem2.setText("3º Ano");
        menuTurmas.add(jMenuItem2);

        jMenuItem4.setText("4º Ano");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        menuTurmas.add(jMenuItem4);

        jMenuItem5.setText("5º Ano");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        menuTurmas.add(jMenuItem5);

        jMenuBar2.add(menuTurmas);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonSair)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(329, Short.MAX_VALUE)
                .addComponent(TituloGestao, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(322, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(184, Short.MAX_VALUE)
                .addComponent(TituloGestao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 185, Short.MAX_VALUE)
                .addComponent(jButtonSair)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemCadAluActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadAluActionPerformed
        AbaCadastroAluno abaCadastroAluno = new AbaCadastroAluno(financeiro, listaAlunos);
        abaCadastroAluno.setVisible(true);
    }//GEN-LAST:event_jMenuItemCadAluActionPerformed

    private void jMenuItemPesAluActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPesAluActionPerformed
        new AbaPesquisarAluno(listaAlunos, financeiro).setVisible(true);  
    }//GEN-LAST:event_jMenuItemPesAluActionPerformed

    private void jMenuItemNotasAluActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNotasAluActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemNotasAluActionPerformed

    private void jMenuItemCadFunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadFunActionPerformed
        new Frames.AbaCadastroFuncionario(financeiro, listaFuncionario).setVisible(true);
    }//GEN-LAST:event_jMenuItemCadFunActionPerformed

    private void jMenuItemPesFunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPesFunActionPerformed
        new Frames.AbaPesquisarFuncionario(listaFuncionario, financeiro).setVisible(true);
    }//GEN-LAST:event_jMenuItemPesFunActionPerformed

    private void jMenuItemProfFunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemProfFunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemProfFunActionPerformed

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jMenuItemRelFinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRelFinActionPerformed
        new Frames.AbaRelatorioFinanceiro(financeiro).setVisible(true);
    }//GEN-LAST:event_jMenuItemRelFinActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        new AbaExibirHorario(primeiro).setVisible(true);

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        new AbaListaAlunos(listaAlunos).setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AbaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AbaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AbaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AbaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new AbaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Label TituloGestao;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItemCadAlu;
    private javax.swing.JMenuItem jMenuItemCadFun;
    private javax.swing.JMenuItem jMenuItemNotasAlu;
    private javax.swing.JMenuItem jMenuItemPesAlu;
    private javax.swing.JMenuItem jMenuItemPesFun;
    private javax.swing.JMenuItem jMenuItemProfFun;
    private javax.swing.JMenuItem jMenuItemRelFin;
    private javax.swing.JMenu menuAlunos;
    private javax.swing.JMenu menuFinanceiro;
    private javax.swing.JMenu menuFuncionarios;
    private javax.swing.JMenu menuTurmas;
    // End of variables declaration//GEN-END:variables
}
